version: "3.8"
services:
  app:
    container_name: outstock
    restart: always
    build:
      context: .
      args:
        JAR_FILE: target/api-0.0.1-SNAPSHOT.jar
    ports:
      - "5000:5000"
    environment:
      DB_HOST: oracle-db
      DB_PORT: 1521
      DB_NAME: GLOBAL_FIAP
      DB_USER: RM552364
      DB_PASSWORD: 180904
    volumes:
      - app_data:/var/lib/app
    networks:
      - outstock_network

  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=180904
      - APP_USER=RM552364
      - APP_USER_PASSWORD=180904
    volumes:
      - oracle_data:/opt/oracle/oradata
    ports:
      - "1521:1521"
    networks:
      - outstock_network

networks:
  outstock_network:

volumes:
  app_data:
  oracle_data:
